gpu_list:
    - 5
seed: null
dump_path: './outputs/'
defaults:
    - data: iwcd_electron
    - data/dataset: iwcd_cnn_short
    - model: regression
    - model/feature_extractor: resnet18
    - model/regression_alg: linear
    - engine: regression
    - tasks/restore_state: restore_state
    - tasks/evaluate: test
    - loss@tasks.evaluate.loss: smooth
    - sampler@tasks.evaluate.data_loaders.test.sampler: subset_sequential
    - _self_
